version: '3'
services:
  angular:
    working_dir: '/root/angular-tour-of-heroes'
    tty: true
    volumes:
      - type: bind
        source: "/mnt/c/Users/USER/docker-angular-hero"
        target: "/root"
    build: ./
    container_name: 'angular'
    ports:
      - "50040:4200"
      - '49153:49153'
    environment:
    - NODE_ENV=dev
    command: ng serve --port 4200 --host 0.0.0.0 --poll 1
    # command: bash -c "npm start"
